### PR TITLE
Add RCAR implementation

### PR DESCRIPTION
**Pull request by tylergiallanza**

### CODE REVIEW

**Comment by mhahsler** [comment]
I think you should use

     class(classifier) <- c('CBA', 'RCAR')

and not provide a custom print method. Make sure you use the correct fields from CBA.object.

**Comment by tylergiallanza** [comment]
Added tests, extended CBA class, and used support/confidence in the new commit.

**Comment by ianjjohnson** [comment]
LGTM. Once Hahsler okays it I’ll merge.

**Comment by mhahsler** [comment]
I think we should have consistent discretization support in CBA, RCAR and whatever else we come up with. CBA does this:
```
####Preparing data####
  if(is(data, "data.frame")){
    #Re-order data to put the class column on the right side, and discretize
    data <- discretizeDF.supervised(formula, data, method=disc.method)
    disc_info <- lapply(data, attr, "discretized:breaks")
}
```
and predict for CBA has:
```
  if(!is.null(object$discretization))
    newdata <- discretizeDF(newdata, lapply(object$discretization,
      FUN = function(x) list(method="fixed", breaks=x)))
```

I think the code can be simplified now since discretizeDF also does this:
```
### discretize new data using the same discretization scheme as the
###   data.frame supplied in methods. Note: NAs may occure if a new 
###   value falls outside the range of values observed in the 
###   originally discretized table (use argument infinity = TRUE in 
###   discretize to prevent this case.) 
discretizeDF(iris[sample(1:nrow(iris), 5),], methods = irisDisc)
```

**Comment by tylergiallanza** [comment]
I added discretization support to the RCAR method. Now you can call either CBA or RCAR on a data.frame that is already discretized or is not discretized.

**Pull request merged**
